[project]
name = "nonebot-plugin-multincm"
version = "0.3.5"
description = "NCM Song Searcher"
authors = [{ name = "student_2333", email = "lgc2333@126.com" }]
dependencies = [
    "nonebot2>=2.0.0",
    "nonebot-adapter-onebot>=2.2.0",
    "pydantic>=1.10.4",
    "pil-utils>=0.1.7",
    "pyncm>=1.6.8.9.1",
    "typing-extensions>=4.5.0",
    "anyio>=3.6.2",
    "nonebot-plugin-apscheduler>=0.2.0",
    "jinja2>=3.1.2",
    "nonebot-plugin-htmlrender>=0.2.0.3",
    "bbcode>=1.1.0",
]
requires-python = ">=3.8,<4.0"
readme = "README.md"
license = { text = "MIT" }

[project.urls]
homepage = "https://github.com/lgc-NB2Dev/nonebot-plugin-multincm"

[tool.pdm.build]
includes = []

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
